### ISSUE TITLE
Reaching out for contact 

### ISSUE THREAD

**Issue by varungujarathi9** [rmens/da-updatescript#1]
Hey Raymon
I am Varun, I am reaching out to you since you contributed to Owncast and I am trying to fix a few links that point to your fork of the repo.

Can you please give me you contact OR alternatively email me at v.gujarathi777@gmail.com?

**Comment by rmens** [comment]
Hey Varun,

I have sent you an e-mail.

**Comment by rmens** [comment]
Haven't heard anything back. Closing.

**Comment by rmens** [comment]
Concern fixed in https://github.com/owncast/owncast.github.io/pull/169

**Comment by varungujarathi9** [comment]
Oh thanks
I was actually working on this and cam across your old commit.
https://github.com/owncast/owncast/issues/3573

---
Thanks & Regards
Varun Gujarathi
(+16697864267)
www.varungujarathi.dev
